remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins

title: Game Tweak

github:
  home_url: https://odiegoduarte.github.io/teste/
  csgo_url: https://odiegoduarte.github.io/teste/pages/teste


---
---

@import "{{ site.theme }}";
